# Generated by Django 5.1 on 2024-08-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0004_riview'),
    ]

    operations = [
        migrations.AddField(
            model_name='riview',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
