# Generated by Django 5.1 on 2024-09-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0007_riview_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='riview',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='riview',
            name='number_rating',
            field=models.IntegerField(default=0),
        ),
    ]
