# Generated by Django 5.1 on 2024-09-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0008_riview_avg_rating_riview_number_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riview',
            name='avg_rating',
        ),
        migrations.RemoveField(
            model_name='riview',
            name='number_rating',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='number_rating',
            field=models.IntegerField(default=0),
        ),
    ]
